micronaut:
  application:
    name: demo


netty:
  default:
    allocator:
      max-order: 3

aerospike:
  host: 127.0.0.1
  port: 3000
  namespace: test

kafka:
  bootstrap:
    servers: localhost:9092

